### ISSUE TITLE
I think it's better to make all other repos `RUCE` depended on to be submodules.

### ISSUE THREAD

**Issue by kinosang** [Rocaloid/RUCE#11]
It's not friendly enough for developers to build `RUCE` from source codes because there're too many repos should be checkout.

**Comment by Sleepwalking** [comment]
Hi kinosang!
@m13253 is actually doing this in [recmake](https://github.com/Rocaloid/RUCE/tree/recmake) branch.

**Comment by kinosang** [comment]
@Sleepwalking Oh, sorry, didn't find out this.
