### ISSUE TITLE
Will RUCE work with QTAU?

### ISSUE THREAD

**Issue by ElonSatoshi** [Rocaloid/RUCE#14]

**Comment by m13253** [comment]
Actually this project is incomplete.
I think it might work with QTAU. But please don't expect anything from RUCE, since it's far from finished.

**Comment by ElonSatoshi** [comment]
So if I try to make an Utau voicebank sing using Qtau, RUCE, and a wavtool, will it work? I heard the *quality* of RUCE in a video, when someone plugged it in to UTAU. It's not the best quality, but that's okay for me. I think that if I can cover songs with Qtau and RUCE, I can attract attention and contribution to both projects.

What kind of difficulties should I expect in this goal? Will I be able to use Teto's voicebank, for example, with Rocaloid and QTAU?

**Comment by tuxzz** [comment]
RUCE should work well with any UTAU-compatible frontend.
Just have a try.
